- demos/Welcome/main.vala
Following the comments in #34 I made the same changes here. Other Vala demos also have formatting problems, but this is the most visible.
> Fix 'Welcome' formatting

- demos/Column View/main.py
This PR adds a Column View demo for Python.
This ended up being way more difficult and ugly than I was expecting because we need an updated release of PyGObject to support Fundamental types like `Gtk.Expression`.
TODO:
> Add Column View Python demo

- demos/Drop Zone/main.py
The code works fine as far as I can see. I followed the JavaScript version closely. Not sure I'm up to date with the latest code style requirements for Python though. The [styleguide](https://github.com/workbenchdev/demos/blob/main/STYLEGUIDE.md) says nothing about Python.
> Port 'Drop Zone' demo to Python

- demos/HTTP Request/main.js
- demos/HTTP Request/main.py
- demos/HTTP Request/main.vala
For porting the demo I followed the JavaScript implementation. Note that the Vala implementation is a bit different, because it handles exceptions. If the implementations should be as close to each other as possible this difference should be resolved eventually, I think.
Like in #62 I made all implementations use the Soup status instead of the status code to avoid magical numbers like `200`.
The Vala implementation didn't work for me, so I fixed it. There seems to be an underlying issue with how Vala code is formatted automatically:
```vala
@"https://api.wikimedia.org/feed/v1/wikipedia/$language/featured/$(date.format ("%Y/%m/%d"))";
```
gets formatted as
```vala
@"https://api.wikimedia.org/feed/v1/wikipedia/$language/featured/$(date.format (" % Y / % m / % d "))";
```
which doesn't work …
> Port 'HTTP Request' demo to Python

- demos/Font Dialog/main.js
- demos/Font Dialog/main.py
I followed the Javascript implementation closely. The latter had some obsolete code in it (`choose_font_and_features` is never called) and I decided to rename `result` to `family` since `result` is already the default argument name for `choose_family_finish` needed for the Python implementation. The demo appears to work fine.
> Port 'Font Dialog' demo to Python

- demos/WebSocket Client/main.vala
Which include:
* Using C-style casting instead of `as` keyword
* Use snake_case to name methods
* Use string formatting for messages
* Use properties instead of their setter/getter methods
> websocket-client: Fixes and improvements to Vala code

- demos/Audio/main.py
The demo works fine. I followed the Javascript implementation, but removed the redundant list of buttons (like in the Vala implementation). Maybe that should be simplified in the Javascript implementation as well.
By the way, the Chopin Nocturne is really beautiful. That was a great choice.
> Port 'Audio' demo to Python

- demos/Map/main.py
There is a `GObject.type_ensure(Shumate.SimpleMap)` in the code, which would be better done in Workbench's Python module. Otherwise the demo works fine. I followed the Javascript implementation.
> Port 'Map' demo to Python

- demos/File Monitor/main.py
I followed the Javascript implementation and the demo seems to work fine.
In `bytes = GLib.Bytes(buffer.props.text.encode())` I used `buffer.props.text` rather than the method `buffer.get_text` since the latter one is more complicated to use and requires multiple parameters according to the doc string:
```python
>>> Gtk.TextBuffer.get_text.__doc__
'get_text(self, start:Gtk.TextIter, end:Gtk.TextIter, include_hidden_chars:bool) -> str'
```
i.e. we would have to write:
```python
buffer.get_text(buffer.get_iter_at_offset(0), buffer.get_iter_at_offset(-1), True)
```
> Port 'File Monitor' demo to Python

- demos/Progress Bar/main.js
- demos/Progress Bar/main.py
The demo works fine. I followed the Javascript implementation and replaced `setInterval()` by `GLib.timeout_add`. 
One question: Wouldn't it be better (for the sake of keeping different implementations close) if the Javascript implementation used the `GLib` function instead of a function which only exists in Javascript?
> Port 'Progress Bar' demo to Python

- demos/Location/main.js
- demos/Location/main.py
I followed the Javascript demo except for using `GLib.DateTime` for getting and formatting the timestamp. That is also done in the Vala implementation and I think Javascript should also use it rather than a Javascript only Date object.
The demo seems to work, although I have to say the accuracy is very low (sometimes the location is off by around 90 km) and the altitude I get (from WIFI data) is worth nothing (it seems to be the smallest float that can be represented, something like -1.7*10^308). It's the same with the Javascript implementation. 
The Vala demo doesn't run on my system, since it can't find `libportal/portal.h`. I would have assumed that having the Vala extension installed should be enough to get all Vala demos running.
> Port 'Location' demo to Python

- demos/Drop Down/main.py
This demo requires Gnome 46 (because of the use of Gtk Expressions). It works fine on Workbench's main branch. I followed the Javascript implementation closely.
> Port 'Drop Down' demo to Python

- demos/Session Monitor and Inhibit/main.py
The demo seems to work. I followed the Javascript implementation except renaming `id` to `identity` (because `id` is a built-in function in Python). There are some warnings, same as in Javascript, when starting a session with at least one action inhibited.
```
(process:108): Gdk-WARNING **: 12:48:11.994: Use gdk_wayland_toplevel_drop_exported_handle()
```
I don't know why that is, but it doesn't seem to affect the demo in other ways.
> Port 'Session Monitor and Inhibit' demo to Python

- demos/View Switcher/main.py
It's my first time contributing to Workbench. Hope it's all good! Waiting for listening to any more suggestions or changes!
> Port View Switcher to python

- src/Animation/main.js
- src/Animation/main.py
Spring animation is not working currently
> Port 'Animation' to Python

- src/List View/code.rs
I am not sure if I should put those comments into the code...
> [Rust] Port the ListView demo

- src/Column View/code.rs
- src/Column View/main.js
This example was quite tricky and I would love to hear some feedback from someone who actually knows how to write rust gtk code :-)
> [Rust] Column View demo ported

- src/Text Fields/code.rs
I was quite verbose on the comments again ... Hope it's ok...
> [Rust] Ported the TextFields demo

- src/Styling with CSS/code.rs
The "my_custom_class" style was unused, but was meant to style the last label
> Use 'my_custom_class" for the programmaticaly set style

- src/Database/main.py
The demo works the same as the Javascript version, I think.
However in the original Database demo #200 by @BharatAtbrat the search by id worked and it does not currently (neither in Javascript nor in Python). This may be due to the "further simplifications" https://github.com/workbenchdev/demos/pull/200/commits/909c833172af65496f068fff6dbaf152fbd3b497 where `findById` got nuked.
Please tell me if that should be made working again.
> Port 'Database' demo to Python
